# .github/workflows/nodejs.yml

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches:
      [main, develop2]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 14.x, 18.x, 20.x, 21.x] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Set up Node.js ver. ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      
      - run: npm run build --if-present

      - name: Run tests
        run: npm test
